[package]
name = "rust-samples"
version = "0.0.1"
authors = ["Alexander Samoilov <alexander.samoilov@gmail.com>"]

[dependencies]
num = "*"

[[bin]]
name = "rust_array_update"
path = "src/rust_array_update.rs"

[[bin]]
name = "kernel_iterator"
path = "src/kernel_iterator.rs"
